name: arabic_made_easy
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  firebase_storage: ^11.0.15
  audioplayers: ^1.1.1
  percent_indicator: ^4.2.2
  animations: ^2.0.7
  dio: ^4.0.6
  enum_to_string: ^2.0.1
  equatable: ^2.0.5
  flutter_hooks: ^0.18.5+1
  google_nav_bar: ^5.0.6
  hooks_riverpod: ^2.1.1
  html_character_entities: ^1.0.0+1
  meta: ^1.8.0
  provider: ^6.0.5
  flutter_tts: ^3.6.3
  shared_preferences: ^2.0.18
  sqflite: ^2.2.5
  path: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/letter_names/
    - assets/letter_sounds/
    - assets/numbers/
    - images/


  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Caveat
      fonts:
        - asset: fonts/Caveat-VariableFont_wght.ttf

    - family: Akaya
      fonts:
        - asset: fonts/AkayaTelivigala-Regular.ttf

    - family: BebasNeue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
        
        