import 'word.dart';

final List<Word> words = [
  Word(
      topic: 'Shapes',
      arabic: 'دائرة',
      english: 'Circle',
      pronunciation: 'Dayira'),
  Word(
      topic: 'Shapes',
      arabic: 'مثلث',
      english: 'Triangle',
      pronunciation: 'Muthalath'),
  Word(
      topic: 'Shapes',
      arabic: 'مربع',
      english: 'Square',
      pronunciation: 'Murabaa'),
  Word(
      topic: 'Shapes',
      arabic: 'مستطيل',
      english: 'Rectangle',
      pronunciation: 'Mustatil'),
  Word(
      topic: 'Shapes',
      arabic: 'خماسي الاضلاع',
      english: 'Pentagon',
      pronunciation: 'Khumasi Aladhla'),
  Word(
      topic: 'Shapes',
      arabic: 'سداسي الاضلاع',
      english: 'Hexagon',
      pronunciation: 'Sudasi Aladhla'),
  Word(
      topic: 'Shapes',
      arabic: 'سباعي',
      english: 'Heptagon',
      pronunciation: 'Subaei'),
  Word(
      topic: 'Shapes',
      arabic: 'مثمن',
      english: 'Octagon',
      pronunciation: 'Muthaman'),
  Word(
      topic: 'Shapes',
      arabic: 'شبه منحرف',
      english: 'Trapezoid',
      pronunciation: 'Shibh Munharif'),
  Word(
      topic: 'Shapes',
      arabic: 'معين',
      english: 'Rhombus',
      pronunciation: 'Mueayan'),
  Word(
      topic: 'Shapes',
      arabic: 'متوازي الاضلاع',
      english: 'Parallelogram',
      pronunciation: 'Mutwazi Aladhla'),
  Word(
      topic: 'Shapes',
      arabic: 'بيضاوي',
      english: 'Oval',
      pronunciation: 'Baydhawi'),
  Word(
      topic: 'Shapes',
      arabic: 'مكور',
      english: 'Sphere',
      pronunciation: 'Mukawar'),
  Word(
      topic: 'Shapes',
      arabic: 'مكعب',
      english: 'Cube',
      pronunciation: 'Mukaeb'),
  Word(
      topic: 'Shapes',
      arabic: 'مكعباني',
      english: 'Cuboid',
      pronunciation: 'Mukabaniun'),
  Word(
      topic: 'Shapes',
      arabic: 'اسطوانة',
      english: 'Cylinder',
      pronunciation: 'Makhroot'),
  Word(
      topic: 'Shapes',
      arabic: 'مخروط',
      english: 'Cone',
      pronunciation: 'Baydhawi'),
  Word(
      topic: 'Shapes',
      arabic: 'هرم',
      english: 'Pyramid',
      pronunciation: 'Harm'),
  Word(
      topic: "Animals",
      arabic: "تمساح",
      english: "Alligator",
      pronunciation: "Timsah"),
  Word(
      topic: "Animals", arabic: "نملة", english: "Ant", pronunciation: "Namla"),
  Word(
      topic: "Animals",
      arabic: "خفاش",
      english: "Bat",
      pronunciation: "Khafash"),
  Word(topic: "Animals", arabic: "دُب", english: "Bear", pronunciation: "Doob"),
  Word(
      topic: "Animals", arabic: "نحلة", english: "Bee", pronunciation: "Nahla"),
  Word(
      topic: "Animals",
      arabic: "طائر",
      english: "Bird",
      pronunciation: "Tayir"),
  Word(
      topic: "Animals",
      arabic: "فراشة",
      english: "Butterfly",
      pronunciation: "Farasha"),
  Word(
      topic: "Animals", arabic: "جمل", english: "Camel", pronunciation: "Jaml"),
  Word(topic: "Animals", arabic: "قطة", english: "Cat", pronunciation: "Qita"),
  Word(
      topic: "Animals",
      arabic: "دجاجة",
      english: "Chicken",
      pronunciation: "Dajaja"),
  Word(
      topic: "Animals",
      arabic: "صرصور",
      english: "Cockroach",
      pronunciation: "Sarsur"),
  Word(
      topic: "Animals",
      arabic: "بقرة",
      english: "Cow",
      pronunciation: "Baqara"),
  Word(
      topic: "Animals",
      arabic: "غزالة",
      english: "Deer",
      pronunciation: "Ghazala"),
  Word(topic: "Animals", arabic: "كلب", english: "Dog", pronunciation: "Kalb"),
  Word(
      topic: "Animals",
      arabic: "دولفين",
      english: "Dolphin",
      pronunciation: "Dulfeen"),
  Word(
      topic: "Animals",
      arabic: "حمار",
      english: "Donkey",
      pronunciation: "Himar"),
  Word(topic: "Animals", arabic: "بطة", english: "Duck", pronunciation: "Bata"),
  Word(
      topic: "Animals", arabic: "نسر", english: "Eagle", pronunciation: "Nasr"),
  Word(
      topic: "Animals",
      arabic: "فيل",
      english: 'Elephant',
      pronunciation: "Fiil"),
  Word(
      topic: "Animals",
      arabic: "سمكة",
      english: "Fish",
      pronunciation: "Samaka"),
  Word(
      topic: "Animals",
      arabic: "ثعلب",
      english: "Fox",
      pronunciation: "Thalab"),
  Word(
      topic: "Animals",
      arabic: "ضفدع",
      english: "Frog",
      pronunciation: "Dhafda"),
  Word(
      topic: "Animals",
      arabic: "زرافة",
      english: "Giraffe",
      pronunciation: "Zarafa"),
  Word(
      topic: "Animals",
      arabic: "معزة",
      english: "Goat",
      pronunciation: "Maeza"),
  Word(
      topic: "Animals",
      arabic: "غورلا",
      english: "Gorilla",
      pronunciation: "Ghurila"),
  Word(
      topic: "Animals",
      arabic: "فرس النهر",
      english: "Hippopotamus",
      pronunciation: "Farass Alnahar"),
  Word(
      topic: "Animals",
      arabic: "حصان",
      english: "Horse",
      pronunciation: "Hisan"),
  Word(
      topic: "Animals",
      arabic: "كنغر",
      english: "Kangaroo",
      pronunciation: "Kanghar"),
  Word(topic: "Animals", arabic: "أسد", english: "Lion", pronunciation: "Asad"),
  Word(
      topic: "Animals",
      arabic: "سحلية",
      english: "Lizard",
      pronunciation: "Sahlia"),
  Word(
      topic: "Animals",
      arabic: "سرطان البحر",
      english: "Lobster",
      pronunciation: "Saratan Albahar"),
  Word(
      topic: "Animals",
      arabic: "قرد",
      english: "Monkey",
      pronunciation: "Qird"),
  Word(
      topic: "Animals",
      arabic: "فأرة",
      english: "Mouse",
      pronunciation: "Fara"),
  Word(
      topic: "Animals",
      arabic: "أخطبوب",
      english: "Octopus",
      pronunciation: "Akhtabut"),
  Word(
      topic: "Animals",
      arabic: "نعامة",
      english: "Ostrich",
      pronunciation: "Naama"),
  Word(topic: "Animals", arabic: "بومة", english: "Owl", pronunciation: "Buma"),
  Word(
      topic: "Animals",
      arabic: "باندا",
      english: "Panda",
      pronunciation: "Banda"),
  Word(
      topic: "Animals",
      arabic: "ببغاء",
      english: "Parrot",
      pronunciation: "Babaghaa"),
  Word(
      topic: "Animals",
      arabic: "بطريق",
      english: "Penguin",
      pronunciation: "Batreeq"),
  Word(
      topic: "Animals",
      arabic: "خنزير",
      english: "Pig",
      pronunciation: "Khanzeer"),
  Word(
      topic: "Animals",
      arabic: "أرنب",
      english: "Rabbit",
      pronunciation: "Arnab"),
  Word(
      topic: "Animals",
      arabic: "راكون",
      english: "Raccoon",
      pronunciation: "Raakoon"),
  Word(
      topic: "Animals",
      arabic: "سمك القرش",
      english: "Shark",
      pronunciation: "Samak Alqirsh"),
  Word(
      topic: "Animals",
      arabic: "غنم",
      english: "Sheep",
      pronunciation: "Ghanam"),
  Word(
      topic: "Animals",
      arabic: "ثعبان",
      english: "Snake",
      pronunciation: "Thueban"),
  Word(
      topic: "Animals",
      arabic: "عنكبوت",
      english: "Spider",
      pronunciation: "Ankabut"),
  Word(
      topic: "Animals",
      arabic: "سنجاب",
      english: "Squirrel",
      pronunciation: "Sinjab"),
  Word(
      topic: "Animals", arabic: "نمر", english: "Tiger", pronunciation: "Nimr"),
  Word(
      topic: "Animals",
      arabic: "سلحفاة",
      english: "Turtle",
      pronunciation: "Sulhafaa"),
  Word(
      topic: "Animals", arabic: "حوت", english: "Whale", pronunciation: "Hoot"),
  Word(topic: "Animals", arabic: "ذئب", english: "Wolf", pronunciation: "Dhib"),
  Word(
      topic: "Animals", arabic: "دودة", english: "Worm", pronunciation: "Duda"),
  Word(
      topic: "Animals",
      arabic: "حمار وحشي",
      english: "Zebra",
      pronunciation: "Himar Wahshi"),
  Word(
      topic: 'Colors',
      arabic: 'أسود',
      english: 'Black',
      pronunciation: 'Aswad'),
  Word(
      topic: 'Colors',
      arabic: 'أبيض',
      english: 'White',
      pronunciation: 'Abyad'),
  Word(topic: 'Colors', arabic: 'أحمر', english: 'Red', pronunciation: 'Ahmar'),
  Word(
      topic: 'Colors', arabic: 'أزرق', english: 'Blue', pronunciation: 'Azraq'),
  Word(
      topic: 'Colors',
      arabic: 'أخضر',
      english: 'Green',
      pronunciation: 'Akhdar'),
  Word(
      topic: 'Colors',
      arabic: 'برتقالي',
      english: 'Orange',
      pronunciation: 'Burtuqali'),
  Word(
      topic: 'Colors', arabic: 'بمبي', english: 'Pink', pronunciation: 'Bambi'),
  Word(
      topic: 'Colors',
      arabic: 'بنفسجي',
      english: 'Purple',
      pronunciation: 'Banafsaji'),
  Word(
      topic: 'Colors',
      arabic: 'أصفر',
      english: 'Yellow',
      pronunciation: 'Asfar'),
  Word(
      topic: 'Colors', arabic: 'بني', english: 'Brown', pronunciation: 'Bunni'),
  Word(
      topic: 'Colors',
      arabic: 'رمادي',
      english: 'Grey',
      pronunciation: 'Ramadi'),
  Word(
      topic: 'Colors',
      arabic: 'عنبر',
      english: 'Amber',
      pronunciation: 'Anbar'),
  Word(
      topic: 'Alphabet',
      arabic: 'أ',
      english: 'Letter 1',
      pronunciation: 'Alif'),
  Word(
      topic: 'Alphabet',
      arabic: 'ب',
      english: 'Letter 2',
      pronunciation: 'Baa'),
  Word(
      topic: 'Alphabet', arabic: 'ت', english: 'Letter 3', pronunciation: 'Ta'),
  Word(
      topic: 'Alphabet',
      arabic: 'ث',
      english: 'Letter 4',
      pronunciation: 'Thaa'),
  Word(
      topic: 'Alphabet',
      arabic: 'ج',
      english: 'Letter 5',
      pronunciation: 'Jeem'),
  Word(
      topic: 'Alphabet',
      arabic: 'ح',
      english: 'Letter 6',
      pronunciation: 'Haa'),
  Word(
      topic: 'Alphabet',
      arabic: 'خ',
      english: 'Letter 7',
      pronunciation: 'Khaa'),
  Word(
      topic: 'Alphabet',
      arabic: 'د',
      english: 'Letter 8',
      pronunciation: 'Daal'),
  Word(
      topic: 'Alphabet',
      arabic: 'ذ',
      english: 'Letter 9',
      pronunciation: 'Thaal'),
  Word(
      topic: 'Alphabet',
      arabic: 'ر',
      english: 'Letter 10',
      pronunciation: 'Raa'),
  Word(
      topic: 'Alphabet',
      arabic: 'ز',
      english: 'Letter 11',
      pronunciation: 'Zaa'),
  Word(
      topic: 'Alphabet',
      arabic: 'س',
      english: 'Letter 12',
      pronunciation: 'Seen'),
  Word(
      topic: 'Alphabet',
      arabic: 'ش',
      english: 'Letter 13',
      pronunciation: 'Sheen'),
  Word(
      topic: 'Alphabet',
      arabic: 'ص',
      english: 'Letter 14',
      pronunciation: 'Saad'),
  Word(
      topic: 'Alphabet',
      arabic: 'ض',
      english: 'Letter 15',
      pronunciation: 'Dhaad'),
  Word(
      topic: 'Alphabet',
      arabic: 'ط',
      english: 'Letter 16',
      pronunciation: 'Taa'),
  Word(
      topic: 'Alphabet',
      arabic: 'ظ',
      english: 'Letter 17',
      pronunciation: 'Dhaa'),
  Word(
      topic: 'Alphabet',
      arabic: 'ع',
      english: 'Letter 18',
      pronunciation: 'Ayn'),
  Word(
      topic: 'Alphabet',
      arabic: 'غ',
      english: 'Letter 19',
      pronunciation: 'Ghayn'),
  Word(
      topic: 'Alphabet',
      arabic: 'ف',
      english: 'Letter 20',
      pronunciation: 'Faa'),
  Word(
      topic: 'Alphabet',
      arabic: 'ق',
      english: 'Letter 21',
      pronunciation: 'Qaaf'),
  Word(
      topic: 'Alphabet',
      arabic: 'ك',
      english: 'Letter 22',
      pronunciation: 'Kaaf'),
  Word(
      topic: 'Alphabet',
      arabic: 'ل',
      english: 'Letter 23',
      pronunciation: 'Laam'),
  Word(
      topic: 'Alphabet',
      arabic: 'م',
      english: 'Letter 24',
      pronunciation: 'Meem'),
  Word(
      topic: 'Alphabet',
      arabic: 'ن',
      english: 'Letter 25',
      pronunciation: 'Noon'),
  Word(
      topic: 'Alphabet',
      arabic: 'ه',
      english: 'Letter 26',
      pronunciation: 'Ha'),
  Word(
      topic: 'Alphabet',
      arabic: 'و',
      english: 'Letter 27',
      pronunciation: 'Waaw'),
  Word(
      topic: 'Alphabet',
      arabic: 'ي',
      english: 'Letter 28',
      pronunciation: 'Yaa'),
  Word(topic: 'Numbers', arabic: '٠', english: 'Zero', pronunciation: 'Sifr'),
  Word(topic: 'Numbers', arabic: '١', english: 'One', pronunciation: 'Wahid'),
  Word(topic: 'Numbers', arabic: '٢', english: 'Two', pronunciation: 'Ithnan'),
  Word(
      topic: 'Numbers',
      arabic: '٣',
      english: 'Three',
      pronunciation: 'Thalatha'),
  Word(topic: 'Numbers', arabic: '٤', english: 'Four', pronunciation: 'Arbaa'),
  Word(topic: 'Numbers', arabic: '٥', english: 'Five', pronunciation: 'Khamsa'),
  Word(topic: 'Numbers', arabic: '٦', english: 'Six', pronunciation: 'Sitta'),
  Word(topic: 'Numbers', arabic: '٧', english: 'Seven', pronunciation: 'Sabaa'),
  Word(
      topic: 'Numbers',
      arabic: '٨',
      english: 'Eight',
      pronunciation: 'Thamania'),
  Word(topic: 'Numbers', arabic: '٩', english: 'Nine', pronunciation: 'Tissaa'),
  Word(topic: 'Numbers', arabic: '١٠', english: 'Ten', pronunciation: 'Ashara'),
  Word(
      topic: 'Numbers',
      arabic: '٢٠',
      english: 'Twenty',
      pronunciation: 'Ashrun'),
  Word(
      topic: 'Numbers',
      arabic: '٣٠',
      english: 'Thirty',
      pronunciation: 'Thalathun'),
  Word(
      topic: 'Numbers',
      arabic: '٤٠',
      english: 'Fourty',
      pronunciation: 'Arbaaun'),
  Word(
      topic: 'Numbers',
      arabic: '٥٠',
      english: 'Fifty',
      pronunciation: 'Khamsun'),
  Word(
      topic: 'Numbers',
      arabic: '٦٠',
      english: 'Sixty',
      pronunciation: 'Sittun'),
  Word(
      topic: 'Numbers',
      arabic: '٧٠',
      english: 'Seventy',
      pronunciation: 'Sabun'),
  Word(
      topic: 'Numbers',
      arabic: '٨٠',
      english: 'Eighty',
      pronunciation: 'Thamanun'),
  Word(
      topic: 'Numbers',
      arabic: '٩٠',
      english: 'Ninety',
      pronunciation: 'Ninety'),
  Word(
      topic: 'Numbers',
      arabic: '١٠٠',
      english: 'A Hundred',
      pronunciation: 'Miaa'),
  Word(
      topic: 'Numbers',
      arabic: '١٠٠٠',
      english: 'A Thousand',
      pronunciation: 'Alf'),
  Word(
      topic: 'Numbers',
      arabic: '١٠٬٠٠٠',
      english: 'Ten Thousand',
      pronunciation: 'Ashra Alaf'),
  Word(
      topic: 'Numbers',
      arabic: '١٠٠٬٠٠٠',
      english: 'A Hundred Thousand',
      pronunciation: 'Miaa Alf'),
  Word(
      topic: 'Numbers',
      arabic: '١٬٠٠٠٬٠٠٠',
      english: 'A Million',
      pronunciation: 'Milyoon'),
  Word(
      topic: 'Body Parts',
      arabic: 'رأس',
      english: 'Head',
      pronunciation: 'Raass'),
  Word(
      topic: 'Body Parts', arabic: 'عين', english: 'Eye', pronunciation: 'Ayn'),
  Word(
      topic: 'Body Parts',
      arabic: 'أذن',
      english: 'Ear',
      pronunciation: 'Udhun'),
  Word(
      topic: 'Body Parts',
      arabic: 'أنف',
      english: 'Nose',
      pronunciation: 'Anf'),
  Word(
      topic: 'Body Parts',
      arabic: 'فم',
      english: 'Mouth',
      pronunciation: 'Fam'),
  Word(
      topic: 'Body Parts',
      arabic: 'شفة',
      english: 'Lips',
      pronunciation: 'Shafa'),
  Word(
      topic: 'Body Parts',
      arabic: 'لسان',
      english: 'Tongue',
      pronunciation: 'Lisan'),
  Word(
      topic: 'Body Parts',
      arabic: 'أسنان',
      english: 'Teeth',
      pronunciation: 'Asnan'),
  Word(
      topic: 'Body Parts',
      arabic: 'رقبة',
      english: 'Neck',
      pronunciation: 'Raqaba'),
  Word(
      topic: 'Body Parts',
      arabic: 'كتف',
      english: 'Shoulder',
      pronunciation: 'Katif'),
  Word(
      topic: 'Body Parts',
      arabic: 'صدر',
      english: 'Chest',
      pronunciation: 'Sadr'),
  Word(
      topic: 'Body Parts',
      arabic: 'بطن',
      english: 'Stomach',
      pronunciation: 'Batn'),
  Word(
      topic: 'Body Parts',
      arabic: 'ظهر',
      english: 'Back',
      pronunciation: 'Dhahr'),
  Word(
      topic: 'Body Parts',
      arabic: 'ذراع',
      english: 'Arm',
      pronunciation: 'Dhiraa'),
  Word(
      topic: 'Body Parts', arabic: 'يد', english: 'Hand', pronunciation: 'Yad'),
  Word(
      topic: 'Body Parts',
      arabic: 'إصبع',
      english: 'Finger',
      pronunciation: 'Issbaa'),
  Word(
      topic: 'Body Parts',
      arabic: 'ساق',
      english: 'Leg',
      pronunciation: 'Saaq'),
  Word(
      topic: 'Body Parts',
      arabic: 'ركبة',
      english: 'Knee',
      pronunciation: 'Rukba'),
  Word(
      topic: 'Body Parts',
      arabic: 'قدم',
      english: 'Foot',
      pronunciation: 'Qadam'),
  Word(
      topic: 'Body Parts',
      arabic: 'أصبع القدم',
      english: 'Toe',
      pronunciation: 'Issbaa Al-Qadam'),
  Word(
      topic: 'Transport',
      arabic: 'سيارة',
      english: 'Car',
      pronunciation: 'Sayyara'),
  Word(
      topic: 'Transport',
      arabic: 'حافلة',
      english: 'Bus',
      pronunciation: 'Hafila'),
  Word(
      topic: 'Transport',
      arabic: 'تكسي',
      english: 'Taxi',
      pronunciation: 'Taxi'),
  Word(
      topic: 'Transport',
      arabic: 'قطار',
      english: 'Train',
      pronunciation: 'Qitar'),
  Word(
      topic: 'Transport',
      arabic: 'طائرة',
      english: 'Airplane',
      pronunciation: 'Tayira'),
  Word(
      topic: 'Transport',
      arabic: 'دراجة نارية',
      english: 'Motorcycle',
      pronunciation: 'Daraja Nariya'),
  Word(
      topic: 'Transport',
      arabic: 'دراجة',
      english: 'Bicycle',
      pronunciation: 'Daraja'),
  Word(
      topic: 'Transport',
      arabic: 'سفينة',
      english: 'Ship',
      pronunciation: 'Safina'),
  Word(
      topic: 'Transport',
      arabic: 'قارب',
      english: 'Boat',
      pronunciation: 'Qarib'),
  Word(
      topic: 'Transport',
      arabic: 'شاحنة',
      english: 'Truck',
      pronunciation: 'Shahina'),
  Word(
      topic: 'Transport',
      arabic: 'مطار',
      english: 'Airport',
      pronunciation: 'Matar'),
  Word(
      topic: 'Transport',
      arabic: 'ميناء',
      english: 'Port',
      pronunciation: 'Minaa'),
  Word(
      topic: 'Transport',
      arabic: 'طريق',
      english: 'Road',
      pronunciation: 'Tariq'),
  Word(
      topic: 'Transport',
      arabic: 'جسر',
      english: 'Bridge',
      pronunciation: 'Jisr'),
  Word(
      topic: 'Transport',
      arabic: 'تقاطع',
      english: 'Intersection',
      pronunciation: 'Taqatuu'),
  Word(topic: 'Cuw', arabic: 'ماء', english: 'Water', pronunciation: 'Maa'),
  Word(topic: 'Cuw', arabic: 'طعام', english: 'Food', pronunciation: 'Taam'),
  Word(topic: 'Cuw', arabic: 'بيت', english: 'House', pronunciation: 'Bayt'),
  Word(topic: 'Cuw', arabic: 'شمس', english: 'Sun', pronunciation: 'Shams'),
  Word(topic: 'Cuw', arabic: 'قمر', english: 'Moon', pronunciation: 'Qamar'),
  Word(topic: 'Cuw', arabic: 'مدينة', english: 'City', pronunciation: 'Madina'),
  Word(topic: 'Cuw', arabic: 'بلد', english: 'Country', pronunciation: 'Balad'),
  Word(topic: 'Cuw', arabic: 'أم', english: 'Mother', pronunciation: 'Umm'),
  Word(topic: 'Cuw', arabic: 'أب', english: 'Father', pronunciation: 'Ab'),
  Word(
      topic: 'Cuw',
      arabic: 'أخوان',
      english: 'Brothers',
      pronunciation: 'Akhwan'),
  Word(
      topic: 'Cuw',
      arabic: 'أخوات',
      english: 'Sisters',
      pronunciation: 'Akhwat'),
  Word(
      topic: 'Cuw',
      arabic: 'أصدقاء',
      english: 'Friends',
      pronunciation: 'Assdeqaa'),
  Word(topic: 'Cuw', arabic: 'عمل', english: 'Work', pronunciation: 'Amal'),
  Word(
      topic: 'Cuw',
      arabic: 'مدرسة',
      english: 'School',
      pronunciation: 'Madrasa'),
  Word(
      topic: 'Cuw',
      arabic: 'جامعة',
      english: 'University',
      pronunciation: 'Jamiaa'),
  Word(
      topic: 'Cuw', arabic: 'طبيب', english: 'Doctor', pronunciation: 'Tabeeb'),
  Word(
      topic: 'Cuw',
      arabic: 'مستشفى',
      english: 'Hospital',
      pronunciation: 'Mustashfa'),
  Word(
      topic: 'Cuw', arabic: 'شارع', english: 'Street', pronunciation: 'Sharii'),
  Word(topic: 'Cuw', arabic: 'سوق', english: 'Market', pronunciation: 'Souq'),
  Word(topic: 'Cuw', arabic: 'كتاب', english: 'Book', pronunciation: 'Kitab'),
  Word(topic: 'Cuw', arabic: 'قلم', english: 'Pen', pronunciation: 'Qalam'),
  Word(
      topic: 'Cuw',
      arabic: 'هاتف',
      english: 'Telephone',
      pronunciation: 'Hatif'),
  Word(topic: 'Cuw', arabic: 'باب', english: 'Door', pronunciation: 'Bab'),
  Word(
      topic: 'Cuw',
      arabic: 'نافذة',
      english: 'Window',
      pronunciation: 'Nafidha'),
  Word(
      topic: 'Cuw', arabic: 'طاولة', english: 'Table', pronunciation: 'Tawila'),
  Word(topic: 'Cuw', arabic: 'كرسي', english: 'Chair', pronunciation: 'Kursi'),
  Word(topic: 'Cuw', arabic: 'سرير', english: 'Bed', pronunciation: 'Sareer'),
  Word(topic: 'Cuw', arabic: 'شاي', english: 'Tea', pronunciation: 'Shai'),
  Word(topic: 'Cuw', arabic: 'قهوة', english: 'Coffee', pronunciation: 'Qahwa'),
  Word(
      topic: 'Cuw',
      arabic: 'حمام',
      english: 'Bathroom',
      pronunciation: 'Hamam'),
  Word(
      topic: 'Cuw',
      arabic: 'مطبخ',
      english: 'Kitchen',
      pronunciation: 'Matbakh'),
  Word(topic: 'Cuw', arabic: 'سفر', english: 'Travel', pronunciation: 'Safar'),
  Word(topic: 'Cuw', arabic: 'بحر', english: 'Sea', pronunciation: 'Bahar'),
  Word(
      topic: 'Cuw', arabic: 'جبل', english: 'Mountain', pronunciation: 'Jabal'),
  Word(topic: 'Cuw', arabic: 'ذهب', english: 'Gold', pronunciation: 'Dhahab'),
  Word(topic: 'Cuw', arabic: 'فضة', english: 'Silver', pronunciation: 'Fidda'),
  Word(
      topic: 'Cuw',
      arabic: 'دواء',
      english: 'Medicine',
      pronunciation: 'Dawaa'),
  Word(topic: 'Cuw', arabic: 'حُب', english: 'Love', pronunciation: 'Hubb'),
  Word(topic: 'Cuw', arabic: 'حرب', english: 'War', pronunciation: 'Harb'),
  Word(
      topic: 'Cuw', arabic: 'عملة', english: 'Currency', pronunciation: 'Umla'),
  Word(topic: 'Cuw', arabic: 'مصرف', english: 'Bank', pronunciation: 'Masraf'),
  Word(topic: 'Cuw', arabic: 'دفع', english: 'Payment', pronunciation: 'Dafaa'),
  Word(
      topic: 'Cuw',
      arabic: 'مستقبل',
      english: 'Future',
      pronunciation: 'Mustaqbal'),
  Word(topic: 'Cuw', arabic: 'قانون', english: 'Law', pronunciation: 'Qanun'),
  Word(topic: 'Cuw', arabic: 'سرقة', english: 'Theft', pronunciation: 'Sariqa'),
  Word(topic: 'Cuw', arabic: 'أمن', english: 'Security', pronunciation: 'Aman'),
];
const List<String> ColorWords = [
  'بنفسجي',
  'أحمر',
  'أصفر',
  'عنبر',
  'رمادي',
  'بمبي',
  'برتقالي',
  'أخضر',
  'أبيض',
  'أسود',
  'أزرق',
  'بني'
];
const List<String> ShapesWords = [
  'دائرة',
  'مثلث',
  'مربع',
  'اسطوانة',
  'بيضاوي',
  'خماسيالاضلاع',
  'سباعي',
  'سداسيالاضلاع',
  'شبهمنحرف',
  'متوازيالاضلاع',
  'مثمن',
  'مخروط',
  'مستطيل',
  'معين',
  'مكعب',
  'مكعباني',
  'مكور',
  'هرم'
];
const List<String> ShapesWordsMulti = [
  'دائرة',
  'مثلث',
  'مربع',
  'اسطوانة',
  'بيضاوي',
  'خماسي الاضلاع',
  'سباعي',
  'سداسي الاضلاع',
  'شبه منحرف',
  'متوازي الاضلاع',
  'مثمن',
  'مخروط',
  'مستطيل',
  'معين',
  'مكعب',
  'مكعباني',
  'مكور',
  'هرم'
];
const List<String> AnimalWordsMulti = [
  'نملة',
  'تمساح',
  'خفاش',
  'دب',
  'دولفين',
  'نحلة',
  'فرس النهر',
  'طائر',
  'فراشة',
  'جمل',
  'قطة',
  'دجاجة',
  'صرصور',
  'بقرة',
  'غزالة',
  'كلب',
  'حمار',
  'بطة',
  'نسر',
  'فيل',
  'سمكة',
  'ثعلب',
  'ضفدع',
  'زرافة',
  'معزة',
  'غورلا',
  'حصان',
  'كنغر',
  'سحلية',
  'سرطان البحر',
  'قرد',
  'فأرة',
  'أخطبوط',
  'نعامة',
  'باندا',
  'ببغاء',
  'بطريق',
  'خنزير',
  'أرنب',
  'راكون',
  'سمك القرش',
  'غنم',
  'ثعبان',
  'عنكبوت',
  'سنجاب',
  'نمر',
  'سلحفاة',
  'حوت',
  'ذئب',
  'دودة',
  'حمار وحشي',
  'بومة',
  'أسد',
];
const List<String> AnimalWords = [
  'نملة',
  'تمساح',
  'خفاش',
  'دب',
  'دولفين',
  'نحلة',
  'فرسالنهر',
  'طائر',
  'فراشة',
  'جمل',
  'قطة',
  'دجاجة',
  'صرصور',
  'بقرة',
  'غزالة',
  'كلب',
  'حمار',
  'بطة',
  'نسر',
  'فيل',
  'سمكة',
  'ثعلب',
  'ضفدع',
  'زرافة',
  'معزة',
  'غورلا',
  'حصان',
  'كنغر',
  'سحلية',
  'سرطانالبحر',
  'قرد',
  'فأرة',
  'أخطبوط',
  'نعامة',
  'باندا',
  'ببغاء',
  'بطريق',
  'خنزير',
  'أرنب',
  'راكون',
  'سمكالقرش',
  'غنم',
  'ثعبان',
  'عنكبوت',
  'سنجاب',
  'نمر',
  'سلحفاة',
  'حوت',
  'ذئب',
  'دودة',
  'حماروحشي',
  'بومة',
  'أسد',
];

const List<String> NumberWords = [
  'صفر',
  'واحد',
  'اثنان',
  'ثلاثة',
  'أربعة',
  'خمسة',
  'ستة',
  'سبعة',
  'ثمانية',
  'تسعة',
  'عشرة',
  'عشرون',
  'ثلاثون',
  'أربعون',
  'خمسون',
  'ستون',
  'سبعون',
  'ثمانون',
  'تسعون',
  'مئة',
  'ألف',
  'عشرةألاف',
  'مئةألف',
  'مليون'
];
const List<String> NumberWordsMulti = [
  'صفر',
  'واحد',
  'اثنان',
  'ثلاثة',
  'أربعة',
  'خمسة',
  'ستة',
  'سبعة',
  'ثمانية',
  'تسعة',
  'عشرة',
  'عشرون',
  'ثلاثون',
  'أربعون',
  'خمسون',
  'ستون',
  'سبعون',
  'ثمانون',
  'تسعون',
  'مئة',
  'ألف',
  'عشرة ألاف',
  'مئة ألف',
  'مليون'
];
const List<String> BodypartsWords = [
  'رأس',
  'عين',
  'أذن',
  'أنف',
  'فم',
  'شفة',
  'لسان',
  'أسنان',
  'رقبة',
  'كتف',
  'صدر',
  'بطن',
  'ظهر',
  'ذراع',
  'يد',
  'إصبع',
  'ساق',
  'ركبة',
  'قدم',
  'أصبعالقدم',
];
const List<String> BodypartsWordsMulti = [
  'رأس',
  'عين',
  'أذن',
  'أنف',
  'فم',
  'شفة',
  'لسان',
  'أسنان',
  'رقبة',
  'كتف',
  'صدر',
  'بطن',
  'ظهر',
  'ذراع',
  'يد',
  'إصبع',
  'ساق',
  'ركبة',
  'قدم',
  'أصبع القدم',
];
const List<String> TransportWords = [
  'سيارة',
  'حافلة',
  'تكسي',
  'قطار',
  'طائرة',
  'دراجةنارية',
  'دراجة',
  'سفينة',
  'قارب',
  'شاحنة',
  'مطار',
  'ميناء',
  'طريق',
  'جسر',
  'تقاطع',
];
const List<String> TransportWordsMulti = [
  'سيارة',
  'حافلة',
  'تكسي',
  'قطار',
  'طائرة',
  'دراجة نارية',
  'دراجة',
  'سفينة',
  'قارب',
  'شاحنة',
  'مطار',
  'ميناء',
  'طريق',
  'جسر',
  'تقاطع',
];
const List<String> CuwWords = [
  'ماء',
  'طعام',
  'بيت',
  'شمس',
  'قمر',
  'مدينة',
  'بلد',
  'أم',
  'أب',
  'أخوان',
  'أخوات',
  'أصدقاء',
  'عمل',
  'مدرسة',
  'جامعة',
  'طبيب',
  'مستشفى',
  'شارع',
  'سوق',
  'كتاب',
  'قلم',
  'هاتف',
  'باب',
  'نافذة',
  'طاولة',
  'كرسي',
  'سرير',
  'شاي',
  'قهوة',
  'حمام',
  'مطبخ',
  'سفر',
  'بحر',
  'جبل',
  'ذهب',
  'فضة',
  'دواء',
  'حب',
  'حرب',
  'عملة',
  'مصرف',
  'دفع',
  'مستقبل',
  'قانون',
  'سرقة',
  'أمن',
];
